/**
 * `aws/rds-data/types` — plain, library-owned types at the RDS Data API
 * operations boundary. None of these carry an `@aws-sdk/client-rds-data`
 * type; every {@link M3LRDSDataOperations} method translates SDK
 * request/response shapes into these before returning. See
 * `docs/reference/aws/rds-data.md` for the full contract.
 *
 * @packageDocumentation
 */

/**
 * A type hint narrowing how a string parameter value is sent to the
 * database. Mirrors the SDK's `TypeHint` enum values verbatim.
 */
export type M3LRDSDataTypeHint =
  "DATE" | "DECIMAL" | "JSON" | "TIME" | "TIMESTAMP" | "UUID";

/**
 * A single column or parameter value, discriminated on `kind`. Preserves the
 * RDS Data API's typed `Field` union (string/long/double/boolean/blob/null)
 * rather than coercing every value to a string — the distinction
 * `aws/athena`'s `AthenaRow = Record<string, string>` discards. Nested array
 * values (the SDK's `arrayValue`) are out of scope for this module's first
 * iteration; a row containing one surfaces as an unmapped column rather than
 * a recursive {@link M3LRDSDataValue}.
 */
export type M3LRDSDataValue =
  | { readonly kind: "null" }
  | { readonly kind: "string"; readonly value: string }
  | { readonly kind: "long"; readonly value: number }
  | { readonly kind: "double"; readonly value: number }
  | { readonly kind: "boolean"; readonly value: boolean }
  | { readonly kind: "blob"; readonly value: Uint8Array };

/** Metadata for one column of a statement's result set. */
export interface M3LRDSDataColumn {
  /** The column's name, or `""` when the SDK response omits it. */
  readonly name: string;
  /** The column's database-specific type name, or `""` when omitted. */
  readonly typeName: string;
  /** The column's display label, or `""` when omitted. */
  readonly label: string;
  /** Whether the column may contain `NULL`, when the SDK reports it. */
  readonly nullable?: boolean;
}

/**
 * One row of a statement's result set: values in the same order as the
 * paired {@link M3LRDSDataColumn} array.
 */
export type M3LRDSDataRow = readonly M3LRDSDataValue[];

/** A single named parameter for a SQL statement. */
export interface M3LRDSDataParameter {
  /** The parameter's name, referenced in the SQL as `:name`. */
  readonly name: string;
  /** The parameter's value. */
  readonly value: M3LRDSDataValue;
  /** An optional type hint narrowing how `value` is sent to the database. */
  readonly typeHint?: M3LRDSDataTypeHint;
}

/** Input for {@link M3LRDSDataOperations.executeStatement}. */
export interface M3LRDSDataStatementInput {
  /** The Aurora Data-API-enabled cluster's Amazon Resource Name (ARN). */
  readonly resourceArn: string;
  /** The Secrets Manager ARN of the secret granting DB access. */
  readonly secretArn: string;
  /** The SQL statement to run. */
  readonly sql: string;
  /** The target database name. */
  readonly database?: string;
  /** The target schema name. */
  readonly schema?: string;
  /** Named parameters referenced in `sql` as `:name`. */
  readonly parameters?: readonly M3LRDSDataParameter[];
  /** An in-flight transaction's id, to run this statement within it. */
  readonly transactionId?: string;
}

/** Result of {@link M3LRDSDataOperations.executeStatement}. */
export interface M3LRDSDataStatementResult {
  /** The result set's rows, `[]` for a non-`SELECT` statement. */
  readonly rows: readonly M3LRDSDataRow[];
  /** The result set's column metadata, `[]` for a non-`SELECT` statement. */
  readonly columns: readonly M3LRDSDataColumn[];
  /** The number of rows inserted/updated/deleted by the statement. */
  readonly numberOfRecordsUpdated: number;
  /** Values generated by the statement (e.g. a `RETURNING` clause). */
  readonly generatedFields: readonly M3LRDSDataValue[];
}

/** Input for {@link M3LRDSDataOperations.batchExecuteStatement}. */
export interface M3LRDSDataBatchInput {
  /** The Aurora Data-API-enabled cluster's Amazon Resource Name (ARN). */
  readonly resourceArn: string;
  /** The Secrets Manager ARN of the secret granting DB access. */
  readonly secretArn: string;
  /** The SQL statement to run once per entry in `parameterSets`. */
  readonly sql: string;
  /** The target database name. */
  readonly database?: string;
  /** The target schema name. */
  readonly schema?: string;
  /** One parameter set per execution of `sql`. */
  readonly parameterSets: readonly (readonly M3LRDSDataParameter[])[];
  /** An in-flight transaction's id, to run this batch within it. */
  readonly transactionId?: string;
}

/** The outcome of one entry in a {@link M3LRDSDataBatchResult}. */
export interface M3LRDSDataUpdateResult {
  /** Values generated by this entry (e.g. a `RETURNING` clause). */
  readonly generatedFields: readonly M3LRDSDataValue[];
}

/** Result of {@link M3LRDSDataOperations.batchExecuteStatement}. */
export interface M3LRDSDataBatchResult {
  /** One result per entry in the batch's `parameterSets`, in order. */
  readonly updateResults: readonly M3LRDSDataUpdateResult[];
}

/**
 * A started transaction, returned by
 * {@link M3LRDSDataOperations.beginTransaction} and consumed by
 * `executeStatement`/`batchExecuteStatement` (via `transactionId`),
 * `commitTransaction`, and `rollbackTransaction`.
 */
export interface M3LRDSDataTransaction {
  /** The transaction's id. */
  readonly transactionId: string;
}
