import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, expectTypeOf, test, vi } from "vitest";

import { runCompletion } from "../src/commands/completion.js";
import type { M3LCliCommandContext } from "../src/commands/context.js";
import { M3LCliError } from "../src/cli/errors.js";
import {
  M3L_CLI_COMPLETION_SHELLS,
  isSafeCompletionToken,
  renderBashCompletion,
  renderFishCompletion,
  renderZshCompletion,
} from "../src/cli/completion-script.js";
import type {
  M3LCliCompletionModel,
  M3LCliCompletionShell,
} from "../src/cli/completion-script.js";
import { discoverScripts } from "../src/discovery/discover.js";
import type { M3LCliScriptCandidate } from "../src/discovery/discover.js";

/**
 * Contract: `src/commands/completion.ts` + `src/cli/completion-script.ts` —
 * `m3l completion <bash|zsh|fish>` (U12, issue #536) prints a self-contained,
 * statically generated completion script. The renderers are pure, so their
 * exact emitted text is asserted directly; the command is asserted for its
 * positional validation, suggestion behaviour and `--json` envelope. See the
 * pinned contract at `docs/reference/cli.md`.
 */

vi.mock("../src/discovery/discover.js", () => ({
  discoverScripts: vi.fn(),
}));

const discoverScriptsMock = vi.mocked(discoverScripts);

afterEach(() => {
  discoverScriptsMock.mockReset();
});

/** Minimal structural stand-in for `M3LCliOutput` — a simple call collector. */
function createOutputCollector(): {
  readonly output: M3LCliCommandContext["output"];
  readonly infoLines: string[];
  readonly errorLines: string[];
} {
  const infoLines: string[] = [];
  const errorLines: string[] = [];
  return {
    output: {
      colorEnabled: false,
      info: (text: string) => {
        infoLines.push(text);
      },
      error: (text: string) => {
        errorLines.push(text);
      },
      heading: () => {
        /* not used by completion */
      },
    },
    infoLines,
    errorLines,
  };
}

function buildContext(overrides: Partial<M3LCliCommandContext> = {}): {
  context: M3LCliCommandContext;
  infoLines: string[];
  errorLines: string[];
} {
  const { output, infoLines, errorLines } = createOutputCollector();
  const context: M3LCliCommandContext = {
    workspaceRoot: "/workspace",
    output,
    jsonOutput: false,
    cacheFilePath: "/workspace/data/cache/m3l-cli/discovery.json",
    historyFilePath: "/workspace/data/cache/m3l-cli/history.json",
    outputDirPath: "/workspace/data/output",
    ...overrides,
  };
  return { context, infoLines, errorLines };
}

function candidate(name: string): M3LCliScriptCandidate {
  return { name, directory: `/workspace/scripts/${name}`, description: "" };
}

/**
 * A deliberately tiny fixed model — every renderer assertion below pins the
 * exact emitted text against this, so a rendering change has to be made on
 * purpose.
 */
const fixedModel: M3LCliCompletionModel = {
  commands: ["completion", "list"],
  scriptCommands: ["inspect"],
  scripts: ["sqs-etl"],
  globalFlags: ["--json", "-h"],
  scriptFlags: ["--in-process"],
};

describe("isSafeCompletionToken", () => {
  test.each(["sqs-etl", "list", "--in-process", "-h", "a.b_c:d", "json-etl2"])(
    "accepts the legitimate token %s",
    (token) => {
      expect(isSafeCompletionToken(token)).toBe(true);
    },
  );

  test.each([
    "a;rm -rf /",
    "a b",
    "$(id)",
    "`id`",
    "a\nb",
    "a'b",
    'a"b',
    "a|b",
    "a&b",
    "",
    "-",
    "--",
  ])("rejects the unsafe token %j", (token) => {
    expect(isSafeCompletionToken(token)).toBe(false);
  });
});

describe("renderBashCompletion", () => {
  test("emits the exact expected script for a fixed model", () => {
    expect(renderBashCompletion(fixedModel)).toEqual([
      "# m3l bash completion — generated by `m3l completion bash`.",
      "# Regenerate after adding a script or changing a script's parameters.",
      "# Do not edit by hand.",
      "",
      "_m3l_commands='completion list'",
      "_m3l_scripts='sqs-etl'",
      "_m3l_script_commands='inspect'",
      "_m3l_global_flags='--json -h'",
      "_m3l_script_flags='--in-process'",
      "_m3l_shells='bash zsh fish'",
      "",
      "_m3l_complete() {",
      '  local cur="${COMP_WORDS[COMP_CWORD]}"',
      '  local command="${COMP_WORDS[1]}"',
      "  COMPREPLY=()",
      "",
      '  if [ "${COMP_CWORD}" -eq 1 ]; then',
      "    # shellcheck disable=SC2207",
      '    COMPREPLY=($(compgen -W "${_m3l_commands} ${_m3l_scripts} ${_m3l_global_flags}" -- "${cur}"))',
      "    return 0",
      "  fi",
      "",
      '  if [ "${command}" = "completion" ]; then',
      "    # shellcheck disable=SC2207",
      '    COMPREPLY=($(compgen -W "${_m3l_shells}" -- "${cur}"))',
      "    return 0",
      "  fi",
      "",
      '  if [ "${COMP_CWORD}" -eq 2 ] && [[ " ${_m3l_script_commands} " == *" ${command} "* ]]; then',
      "    # shellcheck disable=SC2207",
      '    COMPREPLY=($(compgen -W "${_m3l_scripts}" -- "${cur}"))',
      "    return 0",
      "  fi",
      "",
      '  if [[ " ${_m3l_scripts} " == *" ${command} "* ]]; then',
      "    # shellcheck disable=SC2207",
      '    COMPREPLY=($(compgen -W "${_m3l_global_flags} ${_m3l_script_flags}" -- "${cur}"))',
      "    return 0",
      "  fi",
      "",
      "  # shellcheck disable=SC2207",
      '  COMPREPLY=($(compgen -W "${_m3l_global_flags}" -- "${cur}"))',
      "  return 0",
      "}",
      "",
      "complete -F _m3l_complete m3l",
    ]);
  });
});

describe("renderZshCompletion", () => {
  test("emits the exact expected script for a fixed model", () => {
    expect(renderZshCompletion(fixedModel)).toEqual([
      "#compdef m3l",
      "# m3l zsh completion — generated by `m3l completion zsh`.",
      "# Regenerate after adding a script or changing a script's parameters.",
      "# Do not edit by hand.",
      "",
      "_m3l() {",
      "  local -a m3l_commands m3l_scripts m3l_script_commands m3l_global_flags m3l_script_flags m3l_shells",
      "  m3l_commands=('completion' 'list')",
      "  m3l_scripts=('sqs-etl')",
      "  m3l_script_commands=('inspect')",
      "  m3l_global_flags=('--json' '-h')",
      "  m3l_script_flags=('--in-process')",
      "  m3l_shells=('bash' 'zsh' 'fish')",
      "",
      "  if (( CURRENT == 2 )); then",
      "    _describe -t commands 'm3l command' m3l_commands",
      "    _describe -t scripts 'm3l script' m3l_scripts",
      "    _describe -t flags 'm3l flag' m3l_global_flags",
      "    return",
      "  fi",
      "",
      '  local command="${words[2]}"',
      "",
      '  if [[ "${command}" == completion ]]; then',
      "    _describe -t shells 'shell' m3l_shells",
      "    return",
      "  fi",
      "",
      "  if (( CURRENT == 3 )) && (( ${m3l_script_commands[(I)${command}]} )); then",
      "    _describe -t scripts 'm3l script' m3l_scripts",
      "    return",
      "  fi",
      "",
      "  if (( ${m3l_scripts[(I)${command}]} )); then",
      "    _describe -t flags 'm3l flag' m3l_global_flags",
      "    _describe -t flags 'm3l script flag' m3l_script_flags",
      "    return",
      "  fi",
      "",
      "  _describe -t flags 'm3l flag' m3l_global_flags",
      "}",
      "",
      "# Autoloaded from $fpath as `_m3l`, zsh calls this file as the completion",
      "# function itself; sourced by hand, it has to register itself instead.",
      'if [[ "${funcstack[1]}" == _m3l ]]; then',
      '  _m3l "$@"',
      "else",
      "  compdef _m3l m3l",
      "fi",
    ]);
  });
});

describe("renderFishCompletion", () => {
  test("emits the exact expected script for a fixed model", () => {
    expect(renderFishCompletion(fixedModel)).toEqual([
      "# m3l fish completion — generated by `m3l completion fish`.",
      "# Regenerate after adding a script or changing a script's parameters.",
      "# Do not edit by hand.",
      "",
      "complete -c m3l -e",
      "",
      "complete -c m3l -f -n '__fish_use_subcommand' -a 'completion' -d 'm3l command'",
      "complete -c m3l -f -n '__fish_use_subcommand' -a 'list' -d 'm3l command'",
      "complete -c m3l -f -n '__fish_use_subcommand' -a 'sqs-etl' -d 'm3l script'",
      "",
      "complete -c m3l -f -n '__fish_seen_subcommand_from completion' -a 'bash' -d 'shell'",
      "complete -c m3l -f -n '__fish_seen_subcommand_from completion' -a 'zsh' -d 'shell'",
      "complete -c m3l -f -n '__fish_seen_subcommand_from completion' -a 'fish' -d 'shell'",
      "",
      "complete -c m3l -f -n '__fish_seen_subcommand_from inspect' -a 'sqs-etl' -d 'm3l script'",
      "",
      "complete -c m3l -f -n 'true' -l 'json' -d 'm3l flag'",
      "complete -c m3l -f -n 'true' -s 'h' -d 'm3l flag'",
      "complete -c m3l -f -n '__fish_seen_subcommand_from sqs-etl' -l 'in-process' -d 'm3l script flag'",
    ]);
  });

  test("falls back to a `false` condition when no script command is safe", () => {
    const lines = renderFishCompletion({
      ...fixedModel,
      scriptCommands: ["in;spect"],
      scripts: [],
    });
    expect(lines).toContain(
      "# skipped script command 'in?spect' — name is not shell-safe",
    );
    expect(
      lines.some((line) =>
        line.includes("__fish_seen_subcommand_from inspect"),
      ),
    ).toBe(false);
  });
});

describe("every renderer — shell-injection safety", () => {
  const hostileModel: M3LCliCompletionModel = {
    commands: ["list", "a; rm -rf /"],
    scriptCommands: ["inspect"],
    scripts: ["ok-script", "$(id)", "bad\nname"],
    globalFlags: ["--json"],
    scriptFlags: ["--in-process"],
  };

  test.each([
    ["bash", renderBashCompletion],
    ["zsh", renderZshCompletion],
    ["fish", renderFishCompletion],
  ] as const)("%s never interpolates an unsafe token", (_shell, render) => {
    const text = render(hostileModel).join("\n");
    expect(text).toContain("ok-script");
    expect(text).not.toContain("rm -rf /");
    expect(text).not.toContain("$(id)");
    expect(text).not.toContain("bad\nname");
    expect(text).toContain("— name is not shell-safe");
  });

  test("a newline in a rejected name cannot escape its comment line", () => {
    const lines = renderBashCompletion({
      ...hostileModel,
      scripts: ["evil\nrm -rf /"],
    });
    expect(lines).toContain(
      "# skipped script 'evil?rm?-rf??' — name is not shell-safe",
    );
  });
});

describe("runCompletion", () => {
  test("prints the bash script line by line and exits 0", () => {
    discoverScriptsMock.mockReturnValue([candidate("sqs-etl")]);
    const { context, infoLines } = buildContext();

    expect(runCompletion(context, ["bash"])).toBe(0);
    expect(infoLines[0]).toBe(
      "# m3l bash completion — generated by `m3l completion bash`.",
    );
    expect(infoLines.at(-1)).toBe("complete -F _m3l_complete m3l");
    expect(infoLines).toContain("_m3l_scripts='sqs-etl'");
  });

  test("bakes in `completion` itself as a completable command", () => {
    discoverScriptsMock.mockReturnValue([]);
    const { context, infoLines } = buildContext();

    runCompletion(context, ["bash"]);
    const commandsLine = infoLines.find((line) =>
      line.startsWith("_m3l_commands="),
    );
    expect(commandsLine).toContain("completion");
  });

  test("sorts discovered script names so output is byte-stable", () => {
    discoverScriptsMock.mockReturnValue([
      candidate("zeta"),
      candidate("alpha"),
    ]);
    const { context, infoLines } = buildContext();

    runCompletion(context, ["bash"]);
    expect(infoLines).toContain("_m3l_scripts='alpha zeta'");
  });

  test("a bare `m3l completion` is a usage error, exits 2, emits no script", () => {
    discoverScriptsMock.mockReturnValue([]);
    const { context, infoLines, errorLines } = buildContext();

    expect(runCompletion(context, [])).toBe(2);
    expect(errorLines).toEqual([
      "completion requires a <shell> positional — usage: m3l completion <bash|zsh|fish>",
    ]);
    expect(infoLines).toEqual([]);
    expect(discoverScriptsMock).not.toHaveBeenCalled();
  });

  test("an unknown shell throws ERR_CLI_INVALID_PARAMETER_VALUE", () => {
    discoverScriptsMock.mockReturnValue([]);
    const { context } = buildContext();

    let thrown: unknown;
    try {
      runCompletion(context, ["powershell"]);
    } catch (error) {
      thrown = error;
    }

    expect(thrown).toBeInstanceOf(M3LCliError);
    expect((thrown as M3LCliError).code).toBe(
      "ERR_CLI_INVALID_PARAMETER_VALUE",
    );
    expect((thrown as M3LCliError).message).toContain("powershell");
  });

  test("a near-miss shell name suggests the real one", () => {
    discoverScriptsMock.mockReturnValue([]);
    const { context } = buildContext();

    let thrown: unknown;
    try {
      runCompletion(context, ["zshh"]);
    } catch (error) {
      thrown = error;
    }

    expect((thrown as M3LCliError).suggestions).toContain("zsh");
  });

  test("finds the positional regardless of where --json sits", () => {
    discoverScriptsMock.mockReturnValue([]);
    const { context, infoLines } = buildContext({ jsonOutput: true });

    expect(runCompletion(context, ["--json", "fish"])).toBe(0);
    expect(infoLines).toHaveLength(1);
    expect(JSON.parse(infoLines[0] ?? "")).toMatchObject({ shell: "fish" });
  });

  test("--json emits exactly one object carrying `shell` and `script`", () => {
    discoverScriptsMock.mockReturnValue([candidate("sqs-etl")]);
    const { context, infoLines } = buildContext({ jsonOutput: true });

    expect(runCompletion(context, ["zsh", "--json"])).toBe(0);
    expect(infoLines).toHaveLength(1);
    const parsed = JSON.parse(infoLines[0] ?? "") as {
      shell: string;
      script: string;
    };
    expect(parsed.shell).toBe("zsh");
    expect(parsed.script.startsWith("#compdef m3l\n")).toBe(true);
    expect(parsed.script).toContain("sqs-etl");
  });

  test.each(M3L_CLI_COMPLETION_SHELLS)(
    "%s is accepted and produces a non-empty script",
    (shell) => {
      discoverScriptsMock.mockReturnValue([]);
      const { context, infoLines } = buildContext();

      expect(runCompletion(context, [shell])).toBe(0);
      expect(infoLines.length).toBeGreaterThan(0);
    },
  );
});

describe("completion — type contract", () => {
  test("M3LCliCompletionShell is the three-member bash|zsh|fish union", () => {
    expectTypeOf<M3LCliCompletionShell>().toEqualTypeOf<
      "bash" | "zsh" | "fish"
    >();
  });
});

/**
 * The renderers are pure string builders, so nothing above proves the text
 * they emit is *valid* shell. These spawn the real parsers. `fish` is not
 * installed on the development host and is not assumed in CI either, so the
 * fish renderer is covered by the exact-text assertions above only — its
 * syntax is never machine-checked here.
 */
describe("generated scripts parse under their own shell", () => {
  const richModel: M3LCliCompletionModel = {
    commands: ["completion", "doctor", "help", "inspect", "list", "run"],
    scriptCommands: ["inspect", "presets", "run"],
    scripts: ["json-etl", "sqs-etl"],
    globalFlags: ["--json", "--help", "-h", "--version"],
    scriptFlags: ["--in-process", "--dry-run"],
  };

  function hasShell(shell: string): boolean {
    return spawnSync(shell, ["--version"], { stdio: "ignore" }).status === 0;
  }

  function syntaxCheck(
    shell: string,
    lines: readonly string[],
    basename: string,
  ): { status: number | null; stderr: string } {
    const directory = mkdtempSync(join(tmpdir(), "m3l-completion-"));
    try {
      const file = join(directory, basename);
      writeFileSync(file, `${lines.join("\n")}\n`, "utf8");
      const result = spawnSync(shell, ["-n", file], { encoding: "utf8" });
      return { status: result.status, stderr: result.stderr };
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  }

  test.skipIf(!hasShell("bash"))("bash -n accepts the bash script", () => {
    const { status, stderr } = syntaxCheck(
      "bash",
      renderBashCompletion(richModel),
      "m3l.bash",
    );
    expect(stderr).toBe("");
    expect(status).toBe(0);
  });

  test.skipIf(!hasShell("zsh"))("zsh -n accepts the zsh script", () => {
    const { status, stderr } = syntaxCheck(
      "zsh",
      renderZshCompletion(richModel),
      "_m3l",
    );
    expect(stderr).toBe("");
    expect(status).toBe(0);
  });
});
